config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'prototype#index'

  resources :events, only: [:index, :show, :new, :create] do
    resources :comments, :controller => 'event_comments'
    member do
      post :collect
    end
  end



  resources :subjects, only: [:index, :show, :new, :create]


  resources :orders, only: [:index, :show, :new, :create] do
    get :checkout_allpay, :on => :member
    post "notify", on: :member
  end

  resources :hosts

  get 'beta_sign_in' => 'prototype#sign_in', as: :sign_in
  get 'beta_sign_up' => 'prototype#sign_up', as: :sign_up
  get 'main' => 'prototype#main'
  #get 'subjects' => 'prototype#subjects_index', as: :subjects
  #get 'subject/23' => 'prototype#subject_show', as: :show_subject
  get 'dm_poster' => 'prototype#dm_poster'
  get 'host_page' => 'prototype#host_page'
  get 'host_new_subject' => 'prototype#host_new_subject'
  get 'host_new_event' => 'prototype#host_new_event'
  get 'host_promotion' => 'prototype#host_promotion'

end

app/controllers/prototype_controller.rb
class PrototypeController < ApplicationController
  layout :setting_layout

  def index
  end

  def sign_in
  end

  def sign_up
  end

  def main
  end

  def subjects_index
  end

  def subject_show
  end

  def dm_poster

  end

  def host_page
    @events = Event.all
  end

  def host_new_subject

  end

  def host_new_event

  end

  private

  def setting_layout
    case action_name
    when 'index', 'sign_in', 'sign_up'
      'landing'
    when 'main'
      'map_view'
    else
      'application'
    end
  end
end

app/helpers/prototype_helper.rb
module PrototypeHelper
end

app/views/prototype/dm_poster.html.erb
<div class="dm-page-wrapper">
<!-- navigation path -->
  <div class="dm-page-path">
    <span>頁面路徑  / 主辦單位活動列表 / 台北威秀影城</span>
  </div>
  <div class="page-promotion">
    <!-- page poster -->
    <div class="poster-wrapper">

      <!-- <img src="http://blog.techartgroup.com/wp-content/uploads/2014/02/pic_news.jpg" alt=""> -->
      <%= image_tag @event.photos[0].pic.url %>
    </div>
    <!-- page description -->
    <div class="page-description">
      <h2 class="page-title">威秀影城[OPEN OPEN] 電影特映會</h2>
      <ul class="page-info">
        <li>
          <span class="date">活動時間：</span><span><%= @event.start_time %></span>~<span><%= @event.end_time %></span>
        </li>
        <li>
          <span class="event">費用資訊：</span><span>城市通話抽獎</span>
        </li>
        <li>
          <span class="times">活動場次：</span><span>活動只有一場次</span>
        </li>
        <li>
          <span class="organizer">主辦單位：</span><span><%= @event.organizer %></span>
        </li>
        <li>
          <span class="sponsor">主辦人：</span><span><%= @event.hoster %></span>
        </li>
        <li>
          <span class="address">地址：</span><span><%= @event.address %></span>
        </li>
        <li>
          <span class="websit">網址：</span><span><%= @event.website %></span>
        </li>
        <li>
          <span class="email">email：</span><span><%= @event.email %></span>
        </li>
        <li>
          <span class="phone">電話：</span><span><%= @event.contact_phone %></span>
        </li>
      </ul>
      <!-- page price -->
      <div class="page-event-price">
        <span>票價資訊</span>
        <!-- price list -->
        <div class="price actived"><span>NT</span><span class="value">300</span></div>
        <div class="price"><span>NT</span><span class="value">600</span></div>
        <div class="price"><span>NT</span><span class="value">900</span></div>

      </div>
      <!-- options -->
      <div class="page-options-wrapper">
        <ul>
          <li>
            <a href="#" class="option share">
              <span class="content">分享活動</span>
            </a>
          </li>
          <li>
            <a href="#" class="option favorite">
              <span>收藏活動</span>
            </a>
          </li>
          <li>
            <a href="#" class="option join">
              <span>參加活動去</span>
            </a>
          </li>
        </ul>

      </div>
    </div>
  </div>
  <!-- secondary page -->
  <div class="page-secondary">
    <div class="page-editor">
      <div class="ck-editor">
        <%= @event.description %>
      </div>
      <div class="leaveword">
        <span>留言：</span>
        <%= form_for @comment,:url => event_comments_path(@event) do |c|%>
        <!-- <textarea name="leaveword" id="leaveword" cols="30" rows="10"></textarea> -->
        <%= c.text_area :content %>
        <%= c.submit "發表" ,:id =>"commit", :class => "submit" %>
       <!--  <div class="submit">
          <span>送出留言</span>
        </div> -->
        <% end %>
      </div>
      <div class="page-msg-wrapper">
        <% @comments.each do |c|%>
        <div class="unit-wrapper">
          <div class="avatar">
            <%= image_tag current_user.image %>
          </div>
          <span class="name" title="Hey Mike 塞me">
            <%= current_user.name %>
          </span>
          <div class="leave-msg">
            <span>
              <%= c.content %>
            </span>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  <!-- right side shorten dm Klein-->
    <div class="shorten-dm-wrapper">
      <div class="main-title">
        <span>熱門活動</span>
      </div>
      <div class="unit-shorten-cover">
<% @events.each do |e| %>
        <div class="unit-shorten-dm">

          <!-- close button -->
          <i class="shorten-close-btn fa fa-close" role="button"></i>

          <div class="shorten-dm-cover" style="background-image: url(<%=e.photos[0].pic.url %>);">
          </div>
          <div class="info-wrapper">

            <h4 class="title dm"><%=e.title%></h4>
            <!-- shorten dm info -->
            <div class="shorten-dm-info">
              <span class="host">Host：</span>
              <span><%=e.hoster%></span>
            </div>
            <!-- price -->
            <div class="shorten-price">
              <span>Price：</span>
              <!-- price list -->
              <div class="price actived"><span>NT</span><span class="value">300</span></div>
              <div class="price"><span>NT</span><span class="value">600</span></div>
              <div class="price"><span>NT</span><span class="value">900</span></div>
            </div>
            <!-- option -->
            <div class="option-wrapper">
              <a href="#" class="option join">
                <span><%=link_to "參加" , event_path(e)%></span>
              </a>
              <div class="join-count">
                <span><%= number_with_delimiter(rand(1..100000), :delimiter => ","  ) %></span>
                <span>Join it</span>
              </div>
            </div>
          </div>
        </div>
<% end %>
      </div>
    </div>

  </div>

</div>

app/views/prototype/host_new_event.html.erb
<!-- navigation path -->
<div class="host-page-path">
  <span>頁面路徑  / 主辦單位活動列表 / 台北威秀影城</span>
</div>
<!-- main wrapper -->
<div class="new-event-wrapper">
  <div class="new-event">
    <i class="material-icons">accessibility</i><span>HOST | 新建類別</span>
  </div>
<!-- avatar -->
  <div class="avatar-wrapper">
    <div class="image-wrapper">
      <%= image_placeholder width: 100, height: 100, text: 'pic' %>
    </div>
    <span class="user-name">Arthur Reynolds</span>
  </div>
<!-- options -->
  <div class="options">
    <div class="create actived">
      <a href="#">
        <span>Event | 新建活動</span>
      </a>
    </div>
    <div class="create">
      <a href="#">
        <span>Subject | 新建活動</span>
      </a>
    </div>
  </div>
<!-- description -->
  <div class="step-by-step">
    <div class="step-wrapper">
      <span>在JoinFuns建立的活動將獲得優先曝光</span>
      <div class="circle-wrapper">

        <div class="step actived">
          <span class="circle">1</span>
          <span>建立活動資訊</span>
        </div>

        <div class="step">
          <span class="dots">
            <%= image_tag 'dot-dot-bg.png' %>
          </span>
          <span>&nbsp</span>
        </div>

        <div class="step">
          <span class="circle">2</span>
          <span>選取宣傳工具</span>
        </div>

      </div>
    </div>
  </div>

<!-- event input 1st -->

  <form class="event-info">
<!-- drop selection -->
<!-- #TODO -->
    <div class="section-wrapper">
      <div class="drop-section-wrapper">
        <select>
          <option value="" disabled selected>活動類別</option>
          <option value="1">Option 1</option>
          <option value="2">Option 2</option>
          <option value="3">Option 3</option>
        </select>
      </div>
    </div>
    <div class="info-box actived">
      <label for="event-title1">活動主題</label>
      <span><input type="text" id="event-title1"></span>
    </div>
    <div class="info-box">
      <label for="event-title2">主題圖片</label>
      <span>
        <input type="text" id="event-title2">
        <a href="" class="select-file">選取檔案</a>
      </span>
    </div>
    <div class="info-box">
      <label for="event-title3">活動連結</label>
      <span><input type="text" id="event-title3"></span>
    </div>
    <div class="info-box">
      <label for="event-title4">活動地址</label>
      <span><input type="text" id="event-title4"></span>
    </div>

<!-- time machine -->
    <div class="info-box time">
      <div class="inner-wrapper">
        <label for="event-title0">活動開始時間</label>
        <span><input type="time" id="event-title5"></span>
      </div>
    </div>
    <div class="info-box time">
      <div class="inner-wrapper">
        <label for="event-title5">活動結束時間</label>
        <span><input type="time" id="event-title5"></span>
      </div>
    </div>

    <div class="price-option">
      <span><label for="event-title5">活動價格</label></span>
      <a href="#" class="add"><i class="material-icons">add</i></a>
      <a href="#" class="add"><i class="material-icons">add</i></a>
      <a href="#" class="add"><i class="material-icons">add</i></a>
      <span>最多三組價格</span>
    </div>

    <div class="info-box">
      <label for="event-title6">聯絡電話</label>
      <span><input type="text" id="event-title6"></span>
    </div>
    <div class="info-box">
      <label for="event-title7">連絡信箱</label>
      <span><input type="text" id="event-title7"></span>
    </div>

<!-- ck - editor -->
    <div class="editor-wrapper">
      <span>文案編輯</span>
      <div class="editor">
        <span>Editor</span>
      </div>
    </div>

<!-- form option -->
    <div class="form-options">
      <div class="option cancle">
        <a href="#">
          <span>取消建立</span>
        </a>
      </div>
      <div class="option next">
        <a href="#">
          <span>下一步 | 選取宣傳工具</span>
        </a>
      </div>
    </div>

  </form>



</div>

<%= content_for :handwrite_js do %>
  <script>
    $(document).ready(function() {
        $('select').material_select();
      });
  </script>
<% end %>

app/views/prototype/host_new_subject.html.erb
<!-- navigation path -->
<div class="host-page-path">
  <span>頁面路徑  / 主辦單位活動列表 / 台北威秀影城</span>
</div>
<!-- main wrapper -->
<div class="new-subject-wrapper">
  <div class="new-subject">
    <i class="material-icons">accessibility</i><span>HOST | 新建類別</span>
  </div>
<!-- avatar -->
  <div class="avatar-wrapper">
    <div class="image-wrapper">
      <%= image_placeholder width: 100, height: 100, text: 'pic' %>
    </div>
    <span class="user-name">Arthur Reynolds</span>
  </div>
<!-- options -->
  <div class="options">
    <div class="create">
      <a href="#">
        <span>Event | 新建活動</span>
      </a>
    </div>
    <div class="create actived">
      <a href="#">
        <span>Subject | 新建活動</span>
      </a>
    </div>
  </div>
<!-- description -->
  <div class="step-by-step">
    <div class="step-wrapper">
      <span>在JoinFuns建立的活動將獲得優先曝光</span>
      <div class="circle-wrapper">

        <div class="step actived">
          <span class="circle">1</span>
          <span>建立活動資訊</span>
        </div>

        <div class="step">
          <span class="dots">
            <%= image_tag 'dot-dot-bg.png' %>
          </span>
          <span>&nbsp</span>
        </div>

        <div class="step">
          <span class="circle">2</span>
          <span>選取宣傳工具</span>
        </div>

      </div>
    </div>
  </div>

<!-- subject input 1st -->

  <form class="subject-info">
    <div class="info-box actived">
      <label for="subject-title1">活動主題</label>
      <span><input type="text" id="subject-title1"></span>
    </div>
    <div class="info-box">
      <label for="subject-title2">主題圖片</label>
      <span>
        <input type="text" id="subject-title2">
        <a href="" class="select-file">選取檔案</a>
      </span>

    </div>
    <div class="info-box">
      <label for="subject-title3">原始商品連結</label>
      <span><input type="text" id="subject-title3"></span>
    </div>
    <div class="info-box">
      <label for="subject-title4">地址</label>
      <span><input type="text" id="subject-title4"></span>
    </div>

<!-- drop selection -->
<!-- #TODO -->
    <div class="section-wrapper">
      <div class="drop-section-wrapper">
        <select>
          <option value="" disabled selected>結案天數</option>
          <option value="1">Option 1</option>
          <option value="2">Option 2</option>
          <option value="3">Option 3</option>
        </select>
      </div>
    </div>
<!-- subject input 2nd -->
    <div class="info-box">
      <label for="subject-title5">商品價格</label>
      <span><input type="text" id="subject-title5"></span>
    </div>
    <div class="info-box">
      <label for="subject-title6">聯絡電話</label>
      <span><input type="text" id="subject-title6"></span>
    </div>
    <div class="info-box">
      <label for="subject-title7">連絡信箱</label>
      <span><input type="text" id="subject-title7"></span>
    </div>

<!-- ck - editor -->
    <div class="editor-wrapper">
      <span>文案編輯</span>
      <div class="editor">
        <span>Editor</span>
      </div>
    </div>

<!-- form option -->
    <div class="form-options">
      <div class="option cancle">
        <a href="#">
          <span>取消建立</span>
        </a>
      </div>
      <div class="option next">
        <a href="#">
          <span>下一步 | 選取宣傳工具</span>
        </a>
      </div>
    </div>

  </form>



</div>

<%= content_for :handwrite_js do %>
  <script>
    $(document).ready(function() {
        $('select').material_select();
      });
  </script>
<% end %>

app/views/prototype/host_page.html.erb
<div class="host-page-wrapper">
<!-- navigation path -->
  <div class="host-page-path">
    <span>頁面路徑  / 主辦單位活動列表 / 台北威秀影城</span>
  </div>

  <div class="event-wrapper">
<!-- host -->
    <div class="inner-wrapper">
      <div class="host-wrapper">
<!-- header -->
        <div class="header">
          <i class="material-icons">accessibility</i>
          <span>HOST | 主辦單位</span>
        </div>
<!-- avatar -->
        <div class="avatar-wrapper">
          <div class="user-avatar">
            <img src="http://dl.hiapphere.com/data/icon/201409/HiAppHere_com_kov.theme.lumos.png" alt="">
          </div>
          <span>Arthur Reynolds</span>
        </div>
<!-- info detail -->
        <ul class="host-info">
          <li class="address">
            <span>地址</span>
            <span>kjklsdjfkjsdkfdskadsjef fisadjfkasdjf fisadjfkasdjf kdsjfkjds  kdsjfkjds</span>
          </li>
          <li class="website">
            <span>網址</span>
            <span>google.com.tw</span>
          </li>
          <li class="email">
            <span>E-mail</span>
            <span>asdaksdjfkassf@gmial.com</span>
          </li>
          <li class="tel">
            <span>電話</span>
            <span>0912098129048</span>
          </li>
          <li class="descrption">
            <span>描述</span>
            <span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem soluta, quasi natus debitis aut quia dolor repellat aperiam veniam laborum facilis vel unde nihil repudiandae at? Facilis enim unde doloribus.</span>
          </li>
        </ul>
<!-- phtotos -->
        <div class="photos-wrapper">
          <span>相關照片</span>
          <ul>
            <li>
            <!-- rel= 內要放 host id -->
              <a rel="host_id" href="#" class="fancybox">
                <img src="http://dl.hiapphere.com/data/icon/201409/HiAppHere_com_kov.theme.lumos.png" alt="">
              </a>
            </li>
            <li>
              <a rel="host_id" href="http://dl.hiapphere.com/data/icon/201409/HiAppHere_com_kov.theme.lumos.png" class="fancybox">
                <img src="http://dl.hiapphere.com/data/icon/201409/HiAppHere_com_kov.theme.lumos.png" alt="">
              </a>
            </li>
            <li>
              <a rel="host_id" href="http://dl.hiapphere.com/data/icon/201409/HiAppHere_com_kov.theme.lumos.png" class="fancybox">
                <img src="http://dl.hiapphere.com/data/icon/201409/HiAppHere_com_kov.theme.lumos.png" alt="">
              </a>
            </li>
            <li>
              <a rel="host_id" href="http://dl.hiapphere.com/data/icon/201409/HiAppHere_com_kov.theme.lumos.png" class="fancybox">
                <img src="http://dl.hiapphere.com/data/icon/201409/HiAppHere_com_kov.theme.lumos.png" alt="">
              </a>
            </li>
          </ul>
        </div>

      </div>
    </div>

<!-- opening-event -->
    <div class="inner-wrapper">
      <div class="open-wrapper">
<!-- header -->
        <div class="header">
          <i class="material-icons">assistant_photo</i>
          <span>舉辦中</span>
        </div>


        <!-- options -->
      <div class="options">
        <a href="#">
          <span>Event | 活動</span>
        </a>
        <a href="#">
          <span>Subject | 投標</span>
        </a>
      </div>
<!-- partials dm -->
      <% 5.times do %>
        <%= render partial: 'partials/short_dm' %>
      <% end %>
    </div>



    </div>
<!-- expired -->
    <div class="inner-wrapper">
      <div class="expired-wrapper">
<!-- header -->
        <div class="header">
          <i class="material-icons">lock_outline</i>
          <span>過期 | 活動</span>
        </div>

          <!-- options -->
        <div class="options">
          <a href="#">
            <span>Event | 活動</span>
          </a>
          <a href="#">
            <span>Subject | 投標</span>
          </a>
        </div>
        <% 5.times do %>
          <div class="overlay">
            <span>expired</span>
          </div>
          <%= render partial: 'partials/short_dm' %>
        <% end %>


      </div>
    </div>

  </div>

</div>

<%= content_for :handwrite_js do %>
  <script>
$(document).ready(function() {
  $("a.fancybox").fancybox();
});
</script>
<% end %>

app/views/prototype/index.html.erb
<div class="landing-login-options-wrapper">
  <div class="logo">
    <%= image_tag 'logo@2x.png', class: 'responsive-img' %>
  </div>

  <div class="login-options-wrapper">
    <%= link_to user_omniauth_authorize_path(:facebook), class: 'facebook trans-03s', :'data-no-turbolink' => true do %>
      <span>Sign in with Facebook</span>
    <% end %>
    <%= link_to sign_in_path, class: 'email trans-03s' do %>
      <span>Sign in with Email</span>
    <% end %>
  </div>
</div>

app/views/prototype/main.html.erb
<!-- map canvas -->
<div class="map-canvas" id="map"></div>

<!-- user position marker -->
<%= render partial: 'partials/user_position_marker' %>

<!-- panels -->
<%= render partial: 'partials/filter_panel' %>

<!-- dm panels -->
<%= render partial: 'partials/dm_panel' %>


<%= content_for :handwrite_js do %>
  <script>
    $(document).ready(JoinFuns.initialMap());
    $(document).ready(JoinFuns.initMaterialSelect());
    $(document).ready(JoinFuns.filterTriggerInit());
  </script>
<% end %>

app/views/prototype/sign_in.html.erb
<div class="landing-sign-in-form-wrapper">
  <div class="logo">
    <%= image_tag 'logo@2x.png', class: 'responsive-img' %>
  </div>

  <div class="sign-in-form">
    <div class="form">
      <form action="#">
        <div class="input-field">
          <input placeholder="Username" type="text" class="validate">
        </div>
        <div class="input-field">
          <input placeholder="Password" type="password" class="validate">
        </div>

        <%= link_to events_path, class: 'submit-btn', :'data-no-turbolink' => true do %>
          <span>Sign in</span>
        <% end %>
        <!--
        <div class="submit-btn">
          <button>
            Sign in
          </button>
        </div>
        -->
      </form>
    </div>
  </div>

  <div class="sign-up-option-wrapper">
    <a href="#"><i class="material-icons left">help_outline</i> forget password</a>
  </div>
</div>

<div class="landing-divider"></div>

<div class="landing-sign-up-link">
  <span>Don't have an account? <%= link_to 'Sign up', sign_up_path %></span>
</div>

app/views/prototype/sign_up.html.erb
<div class="landing-sign-up-form-wrapper">
  <div class="logo">
    <%= image_tag 'logo@2x.png', class: 'responsive-img' %>
  </div>

  <div class="user-avatar">
    <%= image_tag 'avatar-placeholder.gif', class: 'responsive-img circle' %>
  </div>

  <form action="#">
    <div class="user-name">
      <input type="text" value='John Doe' placeholder="Enter Your Name Here">
    </div>
    <div class="file-field input-field">
      <div class="btn select-photo">
        <span>change photo</span>
        <input type="file">
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>

    <div class="sign-up-form">
      <div class="input-field">
        <input placeholder="Email" type="text" class="validate">
      </div>
      <div class="input-field">
        <input placeholder="Password" type="password" class="validate">
      </div>
      <div class="input-field">
        <input placeholder="Confirm Password" type="password" class="validate">
      </div>
      <div class="input-field">
        <input placeholder="Cell Phone" type="tel" class="validate">
      </div>
      <div class="input-field">
        <input placeholder="Birthday" type="text" class="validate">
      </div>
      <div class="subscribe">
        <p>
          <input type="checkbox" id="test" checked="checked" />
          <label for="test">Subscribe News</label>
        </p>
      </div>

      <%= link_to events_path, class: 'submit-btn', :'data-no-turbolink' => true do %>
        <span>GO!</span>
      <% end %>
      <!--
      <div class="submit-btn">
        <button>
          Sign in
        </button>
      </div>
      -->

    </div>
  </form>

app/views/prototype/subject_show.html.erb
<div class="subject-detail-wrapper">
  <div class="subjects-container">
    <div class="navigation-option">
      <%= link_to '< Back To List', subjects_path, class: 'back-to-list waves-effect waves-light btn left' %>
    </div>

    <div class="subject-info-banner">
      <div class="picture-cover">
        <%= image_tag 'subject-detail-banner.jpg', class: 'responsive-img' %>
      </div>
      <div class="info-detail">
        <h3>Groningen</h3>

        <div class="points-info">
          <span>單標點數：</span><span> <%= rand(1..50) %> 點</span>
        </div>

        <div class="product-link">
          <a href="#">商品來源連結</a>
        </div>

        <div class="progress-info-wrapper">
          <span>標案進度：</span>
          <div class="progress">
            <% progress = rand(5..100) %>
            <div class="determinate" style="width: <%= progress %>%"></div>
          </div>
          <span class="progress-value">
            <%= progress %>%
          </span>
        </div>

        <span>截標時間：</span>
        <div class="time-info-wrapper">
          <div class="hour">
            <span class='value'><%= rand(0..23).to_s.rjust(2, '0') %></span>
            <span class="unit">hr</span>
          </div>
          <div class="minute">
            <span class='value'><%= rand(0..59).to_s.rjust(2, '0') %></span>
            <span class="unit">min</span>
          </div>
          <div class="second">
            <span class='value'><%= rand(0..59).to_s.rjust(2, '0') %></span>
            <span class="unit">sec</span>
          </div>
        </div>

        <form action="#">
          <div class="input-field col s6">
            <input placeholder="" id="first_name" type="number" class="validate">
            <label for="first_name">下標點數</label>
          </div>
          <button type="submit" class="btn">下標</button>
        </form>
      </div>
    </div>
  </div>
  <div class="subject-description-wrapper subjects-container">
    <span>詳細資訊</span>
    <h4>Groningen</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa consectetur non atque mollitia numquam neque nulla quae facere illum ab ea veniam eveniet rerum iste temporibus aliquid, fugiat doloremque ipsam sint! Modi qui repellendus aliquam, illum inventore odit sapiente adipisci doloribus perspiciatis, nesciunt velit dolores nostrum. Enim praesentium eveniet esse omnis eius, cum ipsam! Repellendus veritatis ratione ipsum labore numquam fugit ex quidem consequatur, dolore! Doloremque, dolorem at nesciunt repellendus nisi et aspernatur tempora. Commodi, quidem voluptatum consequuntur maiores cumque esse velit! Ut, neque quaerat dolorem, minima praesentium quas vitae eos illo fugiat inventore dolorum, harum obcaecati, nisi quasi ipsam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea facilis quo rerum nam modi sunt sed id accusantium magnam perspiciatis recusandae quae iste, nihil ab officia, qui, quidem consectetur odio nemo ipsam animi obcaecati quas. Facere, nemo, debitis. Libero quo tenetur, ipsa laborum, rerum doloremque vel repudiandae iure accusantium quia adipisci sit omnis dolor minima itaque nam, aliquam iste corporis quis magni. Dicta vel in velit eius accusantium nesciunt odit porro similique laudantium, quam quisquam dignissimos magni voluptatibus, nemo saepe. Quisquam modi placeat quidem voluptates eaque rem laudantium velit adipisci facilis consequuntur, tempora odio cupiditate perferendis debitis esse non harum sequi error unde id. Officia quisquam corrupti, nesciunt, blanditiis fugiat quaerat ab. Odio deleniti obcaecati ab aspernatur amet corporis, laborum atque expedita, iusto eos et quidem, recusandae consequatur voluptatum maiores corrupti animi exercitationem labore sunt sit adipisci! Totam ducimus atque, sapiente quaerat sunt, velit aut repellat! Facere consequuntur repellat praesentium modi dignissimos non similique, quae voluptatum amet, perspiciatis ipsum dolores nesciunt nisi inventore, fugit! Porro enim adipisci officia aperiam non, doloremque reiciendis voluptas, qui omnis. Explicabo obcaecati iure et nesciunt ea, facilis expedita quod doloremque, non veritatis consequatur libero iste ducimus, cumque laudantium similique id a fugiat dolor est fugit.</p>
  </div>
</div>

app/views/prototype/subjects_index.html.erb
<div class="subjects-index-wrapper">
  <div class="subjects-container">
    <% 20.times.each do %>
      <div class="subject-unit">
        <div class="subject-inner trans-03s">
          <div class="subject-cover-wrapper" style="background-image: url(<%= asset_url('subject-cover.jpg') %>);"></div>
          <div class="subject-info-wrapper">
            <h3>Groningen</h3>

            <div class="progress">
              <% progress = rand(5..100) %>
              <div class="determinate" style="width: <%= progress %>%"></div>
            </div>
            <span class="progress-value">
              <%= progress %>%
            </span>

            <div class="time-info-wrapper">
              <div class="hour">
                <span class='value'><%= rand(0..23).to_s.rjust(2, '0') %></span>
                <span class="unit">hr</span>
              </div>
              <div class="minute">
                <span class='value'><%= rand(0..59).to_s.rjust(2, '0') %></span>
                <span class="unit">min</span>
              </div>
              <div class="second">
                <span class='value'><%= rand(0..59).to_s.rjust(2, '0') %></span>
                <span class="unit">sec</span>
              </div>
            </div>

            <div class="get-button">
              <%= link_to 'Get', show_subject_path %>
              <!-- <a href="#">Get</a> -->
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>