config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'prototype#index'

  resources :events, only: [:index, :show, :new, :create] do
    resources :comments, :controller => 'event_comments'
    member do
      post :collect
    end
  end



  resources :subjects, only: [:index, :show, :new, :create]


  resources :orders, only: [:index, :show, :new, :create] do
    get :checkout_allpay, :on => :member
    post "notify", on: :member
  end

  resources :hosts

  get 'beta_sign_in' => 'prototype#sign_in', as: :sign_in
  get 'beta_sign_up' => 'prototype#sign_up', as: :sign_up
  get 'main' => 'prototype#main'
  #get 'subjects' => 'prototype#subjects_index', as: :subjects
  #get 'subject/23' => 'prototype#subject_show', as: :show_subject
  get 'dm_poster' => 'prototype#dm_poster'
  get 'host_page' => 'prototype#host_page'
  get 'host_new_subject' => 'prototype#host_new_subject'
  get 'host_new_event' => 'prototype#host_new_event'
  get 'host_promotion' => 'prototype#host_promotion'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :photos
  has_many :comments
  has_many :prices
  has_many :collects
  belongs_to :user
  has_many :user_collects, :through => :collects, :source => :user
  accepts_nested_attributes_for :photos
  accepts_nested_attributes_for :prices

  as_enum :category, event: 0, dm: 1


  geocoded_by :address
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  is_impressionable :counter_cache => true, :unique => true

  has_attached_file :cover, :styles => { :medium => "600x600>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/

  def self.search(args)
    address = args[:address]
    keyword = args[:keyword]
    combine_keyword = args[:combine_keyword]
    time_code = args[:time].to_i
    latitude = args[:latitude]
    longitude = args[:longitude]
    distance = args[:distance]



    # where(:title, query) -> This would return an exact match of the query
    filtered_events = Event.all

    #where("address like ?", "%#{address}%") unless address.blank?
    filtered_events = filtered_events.where("address like ? or title like ?", "%#{combine_keyword}%", "%#{combine_keyword}%" ) if combine_keyword.present?
    filtered_events = filtered_events.where("address like ?", "%#{address}%" ) if address.present?
    filtered_events = filtered_events.where("title like ?", "%#{keyword}%") if keyword.present?
    filtered_events = filter_by_time(code: time_code, collection: filtered_events) if time_code.present?
    filtered_events = filtered_events.near([latitude,longitude],distance, :units=>:km) if distance.present?
    filtered_events
  end

  private

  def self.filter_by_time(args)
    code = args[:code]
    collection = args[:collection]
    current_time = Time.zone.now

    case code
    when 0
      collection.between_times(current_time - 1.weeks, current_time)
    when 1
      collection.between_times(current_time - 2.weeks, current_time)
    when 2
      collection.between_times(current_time - 4.weeks, current_time)
    when 3
      collection.between_times(current_time - 24.weeks, current_time)
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout :setting_layout
  impressionist :actions=>[:show]

  def index

    set_events
    events_order

    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
      #address=Geocoder.coordinates(event.address)
      marker.lat event.latitude
      marker.lng event.longitude
      marker.json({ :id => event.id })
      marker.picture({
        :url => view_context.image_path("#{event.category}-icon@2x.png"),
        :width   => 86,
        :height  => 102
      })
    end

  end

  def show
    @event = Event.find(params[:id])
    #@hit_count = @event.impressionist_count(:filter=>:ip_address)
    @events = Event.includes(:photos, :prices).all # TODO, show filter out hotest events
    #@sticker = Geocoder.coordinates(@event.address)
    #gon.sticker = @sticker
    # respond_to do |format|
    #   format.html
    #   format.js
    # end
    @comment = Comment.new
    @comments = @event.comments.order("created_at desc")
    # render "prototype/dm_poster"
    @collect = get_collect
  end

  def new
    @event= Event.new

    #8.times{ @event.photos.build }
    3.times{ @event.prices.build }
  end

  def create
    @event= Event.new(event_params)
    @event.user = current_user
    category = view_context.te(@event, :category)

    if @event.save
      flash[:success] = "#{category} 已成功建立！"
      redirect_to events_path
    else
      flash[:error] = "請檢查欄位後再試一次。"
      render :new
    end
  end

  def collect

    @event = Event.find(params[:id])

    collect = get_collect

    if collect
      collect.destroy
    else
      current_user.collects.create!( :event => @event )
    end

    respond_to do |format|
     format.html {
       redirect_to event_path(@event)
     }
     format.js
    end


  end

  # def search
  #   @events = @events.where("address like ?", params[:address]) unless address.blank?
  #   @events = @events.where("title like ?", params[:keyword]) unless keyword.blank?
  #   @events
  # end

  private

  def event_params
    params.require(:event).permit(:title, :category, :contact_phone, :email, :website, :organizer, :price, :event_type, :description, :address, :hoster, :start_time, :end_time, :cover, :budget, :showtime, prices_attributes:[:price])
  end

  def setting_layout
    case action_name
    when 'index'
      'map_view'
    else
      'application'
    end
  end

  def set_events
    address = params[:address]
    keyword = params[:keyword]
    combine_keyword = params[:combine_keyword]
    time = params[:time]
    distance = params[:distance]
    latitude = cookies[:lat]
    longitude = cookies[:lng]

    return @events = Event.includes(:photos, :prices).search(combine_keyword: combine_keyword, time: time, keyword: keyword, address: address, distance: distance, latitude: latitude, longitude: longitude) if params[:search]
    @events = Event.includes(:photos, :prices).all
  end

  def events_order

    if params[:order]

      sort_by = case params[:order]
        when 'hottest'
          'impressions_count DESC '
        when 'newest'
          'created_at DESC'
      end

      @events = @events.order(sort_by)
    else
      @events = @events.order("events.id desc")
    end

  end

  def get_collect

    current_user.collects.find_by_event_id( params[:id] )

  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/collect.js.erb
var text=$(".favorite span").text()

if (text==="收藏活動"){
 $(".favorite span").text("取消收藏")
 alert("收藏成功")
}
else{
 $(".favorite span").text("收藏活動")
 alert("已取消收藏")
}

app/views/events/index.html.erb
<!-- map canvas -->
<div class="map-canvas" id="map"></div>

<!-- user position marker -->
<%= render partial: 'partials/user_position_marker' %>

<!-- panels -->
<%= render partial: 'partials/filter_panel' %>

<!-- dm notifier style panel -->
<%= render partial: 'partials/dm_notifier' %>

<%= content_for :handwrite_js do %>
  <script>

      handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){

      if(navigator.geolocation)
      navigator.geolocation.getCurrentPosition(getpos);

      function getpos(pos){
        var pin = handler.addMarker({
          lat: pos.coords.latitude,
          lng: pos.coords.longitude
        });
        handler.map.centerOn(pin);
        document.cookie= 'lat=' + escape(pos.coords.latitude)
        document.cookie= 'lng=' + escape(pos.coords.longitude)


      }


      markers_json = <%=raw @hash.to_json %>;
      markers = _.map(markers_json, function(marker_json){
        marker = handler.addMarker(marker_json);
        _.extend(marker, marker_json);
        return marker;
      });

      handler.bounds.extendWith(markers);
      //handler.fitMapToBounds();
      handler.getMap().setZoom(19);
      console.log(handler)



      // Add event listener on marker click
      for (var i = 0; i <  markers.length; ++i) {
        var marker = markers[i];
        google.maps.event.addListener(marker.serviceObject, 'click', onMarkerClick(marker, event));
      }

    })

    //$(document).ready(JoinFuns.initialMap());
    $(document).ready(JoinFuns.initMaterialSelect());
    $(document).ready(new JoinFuns.FilterPanel);
    $(document).ready(new JoinFuns.Notifiers);
  </script>
<% end %>

app/views/events/index.js.erb
<%= @latitude=params[:latitude]%>
<%= @longitude=params[:longitude]%>

app/views/events/new.html.erb
<!-- navigation path -->
<!-- <div class="host-page-path">
  <span>頁面路徑  / 主辦單位活動列表 / 台北威秀影城</span>
</div> -->
<!-- main wrapper -->
<div class="new-event-wrapper">
  <div class="new-event">
    <i class="material-icons">accessibility</i><span><%=current_user.name%> | 新建活動</span>
  </div>
<!-- avatar -->
  <div class="avatar-wrapper">
    <div class="image-wrapper">
     <%= image_tag current_user.image ,width: 100, height: 100 %>
      <%#= image_placeholder width: 100, height: 100, text: 'pic' %>
    </div>
    <span class="user-name"><%=current_user.name%></span>
  </div>

  <%=form_for @event, :html => {:class => "event-info"} do |f|%>
   <div class="event-form">
<!-- options -->
  <div class="options">
    <div class="create actived">
      <a href="#">
        <span>Event | 新建活動</span>
      </a>
    </div>
    <div class="create">
      <%=link_to new_subject_path do %>
        <span>Subject | 新建標案</span>
      <% end %>
    </div>
  </div>

<!-- description -->
  <div class="step-by-step">
    <div class="step-wrapper">
      <span>在JoinFuns建立的活動將獲得優先曝光</span>
      <div class="circle-wrapper">

        <div class="step actived">
          <span class="circle">1</span>
          <span>建立活動資訊</span>
        </div>

        <div class="step">
          <span class="dots">
            <%= image_tag 'dot-dot-bg.png' %>
          </span>
          <span>&nbsp</span>
        </div>

        <div class="step">
          <span class="circle">2</span>
          <span>選取宣傳工具</span>
        </div>

      </div>
    </div>
  </div>

<!-- event input 1st -->

  <!-- <form class="event-info"> -->
<!-- drop selection -->
<!-- #TODO -->

    <div class="section-wrapper">
      <div class="drop-section-wrapper">
        <select>
          <option value="" disabled selected>活動類別</option>
          <option value="1">Option 1</option>
          <option value="2">Option 2</option>
          <option value="3">Option 3</option>
        </select>
      </div>
    </div>
    <div class="info-box actived">
      <label for="event-title1">活動主題</label>
      <span> <%= f.text_field :title %></span>
    </div>
    <div class="info-box">
      <label for="event-title2">主題圖片</label>
      <span>
        <!-- <input type="text" id="event-title2"> -->
        <%= f.file_field :cover %>
        <!-- <a href="" class="select-file">選取檔案</a> -->
      </span>
    </div>
    <div class="info-box">
      <label for="event-title3">活動連結</label>
      <span> <%= f.text_field :website %></span>
    </div>
    <div class="info-box">
      <label for="event-title4">活動地址</label>
      <span> <%= f.text_field :address %></span>
    </div>

<!-- time machine -->
    <div class="info-box time">
      <div class="inner-wrapper">
        <label for="event-title0">活動開始時間</label>
        <span><%= f.date_field :start_time, class: 'datepicker date' %></span>
      </div>
    </div>
    <div class="info-box time">
      <div class="inner-wrapper">
        <label for="event-title5">活動結束時間</label>
        <span><%= f.date_field :end_time, class: 'datepicker date'%></span>
      </div>
    </div>

    <div class="price-option">
      <span><label for="event-title5">活動價格</label></span>
      <!-- <a href="#" class="add"><i class="material-icons">add</i></a>
      <a href="#" class="add"><i class="material-icons">add</i></a>
      <a href="#" class="add"><i class="material-icons">add</i></a> -->
      <%= f.fields_for :prices do |price| %>

          <span><%= price.text_field :price,class: 'add' %></span>


      <% end %>
      <span>最多三組價格</span>
    </div>

    <div class="info-box">
      <label for="event-title6">聯絡電話</label>
      <span> <%= f.text_field :contact_phone %></span>
    </div>
    <div class="info-box">
      <label for="event-title7">連絡信箱</label>
      <span> <%= f.text_field :email %></span>
    </div>

<!-- ck - editor -->
    <div class="editor-wrapper">
      <span>文案編輯</span>
      <div class="editor">
        <%= f.text_area :description, rows: '3' %>
      </div>
    </div>

<!-- form option -->
    <div class="form-options">
      <div class="option cancle">
        <%= link_to events_path , :'data-no-turbolink' => true do%>
          <span>取消建立</span>
        <% end %>
      </div>
      <div class="option next">
        <a href="#">
          <span>下一步 | 選取宣傳工具</span>
        </a>
      </div>
    </div>
    </div>

<%= render :partial => "partials/promotion" ,:locals => { :f => f }%>
  <%end%>
  <!-- </form> -->



</div>


<%= content_for :handwrite_js do %>
  <script>
    $(document).ready(function() {
      $('.ckeditor').ckeditor({

  // optional config
      });
        $('select').material_select();
        JoinFuns.initMaterialDatepicker();
         $('.new-promo-wrapper').hide();
        $('.next').on("click",function(){
          $('.event-form').hide();
          $('.new-promo-wrapper').show();
        });
        $('.cancle').on("click",function(){
          $('.new-promo-wrapper').hide();
          $('.event-form').show();
        })
      });
  </script>
<% end %>

app/views/events/old_new.html.erb
<div class="new-event-form-wrapper">
  <%= form_for @event ,:html => { :multipart => true } do |f|  %>
    <div class="new-event-form row">

      <div class="input-field">
        <%= f.text_field :title, placeholder: '活動標題' %>
      </div>

      <div class="input-field">
        <%= f.text_field :organizer, placeholder: '主辦單位' %>
      </div>

      <div class="input-field">
        <%= f.text_field :hoster, placeholder: '主辦人' %>
      </div>

      <div class="input-field">
        <%= f.text_field :address, placeholder: '活動地址' %>
      </div>

      <div class="input-field">
        <%= f.text_field :contact_phone, placeholder: '聯絡電話' %>
      </div>

      <div class="input-field">
        <%= f.text_field :email, placeholder: 'Email' %>
      </div>

      <div class="input-field">
        <%= f.text_field :website, placeholder: '網站' %>
      </div>

      <!-- <div class="input-field">
        <%= f.text_field :price, placeholder: '活動費用' %>
      </div -->>

      <div class="input-field">
        <%= f.date_field :start_time, class: 'datepicker date', placeholder: '活動開始時間' %>
      </div>

      <div class="input-field">
        <%= f.date_field :end_time, class: 'datepicker date', placeholder: '活動結束時間' %>
      </div>

      <div class="input-field">
        <%= f.select :category, enum_option_pairs(Event, :category), {include_blank: '請選擇類型'} %>
      </div>

      <div class="input-field">
        <%= f.text_area :description, rows: '10', placeholder: '活動描述', :class => "ckeditor" %>
      </div>

      <%= f.fields_for :prices do |price| %>
        <div class="input-field">
          <%= price.text_field :price, placeholder: '活動費用' %>
        </div>

      <% end %>

      <%= f.fields_for :photos do |photo| %>
        <div class="file-field input-field">
          <input class="file-path validate" type="text"/>
          <div class="btn">
            <span>活動圖片</span>
            <!-- <input type="file" /> -->
            <%= photo.file_field :pic %>
          </div>
        </div>
      <% end %>

      <div class="submit-btn">
        <%= button_tag type: 'submit', data: {disable_with: "資料上傳中 <i class='fa fa-circle-o-notch fa-spin'></i>"} do %>
          送出資料
        <% end %>
      </div>

    </div>
  <% end %>
</div>


<%= content_for :handwrite_js do %>
  <script>
    $('.ckeditor').ckeditor({

  // optional config
    });
    $(document).ready(JoinFuns.initMaterialSelect());
    $(document).ready(JoinFuns.initMaterialDatepicker());
  </script>
<% end %>

app/views/events/promotion.html.erb
<!-- navigation path -->
<!-- <div class="host-page-path">
  <span>頁面路徑  / 主辦單位活動列表 / 台北威秀影城</span>
</div> -->
<!-- main wrapper -->
<!-- <div class="new-promo-wrapper">
  <div class="new-promo">
    <i class="material-icons">accessibility</i><span>HOST | 新建類別</span>
  </div> -->
<!-- avatar -->
 <!--  <div class="avatar-wrapper">
    <div class="image-wrapper">
      <%#= image_placeholder width: 100, height: 100, text: 'pic' %>
    </div>
    <span class="user-name">Arthur Reynolds</span>
  </div> -->
<!-- options -->
 <!--  <div class="options">
    <div class="create">
      <a href="#">
        <span>宣傳工具</span>
      </a>
    </div>
  </div> -->
<!-- description -->
 <!--  <div class="step-by-step">
    <div class="step-wrapper">
      <span>在JoinFuns建立的活動將獲得優先曝光</span>
      <div class="circle-wrapper">

        <div class="step">
          <span class="circle">1</span>
          <span>建立活動資訊</span>
        </div>

        <div class="step">
          <span class="dots">
            <%#= image_tag 'dot-dot-bg.png' %>
          </span>
          <span>&nbsp</span>
        </div> -->

<!-- #TODO dot-dot-dot -->
     <!--    <div class="step actived">
          <span class="circle">2</span>
          <span>選取宣傳工具</span>
        </div>

      </div>
    </div>
  </div> -->

<!-- promo input 1st -->

  <div class="promo-info">

    <div class="info-box">
      <span class="title">帳戶餘額</span>
      <span class="balance">NT 20,000</span>
    </div>

<!-- option for -->
    <div class="deposit-wrapper">
      <a href="#" class="option">
        <span>立即儲值</span>
      </a>
    </div>


    <div class="budget-wrapper">
      <div class="budget">
        <div class="free-promo">
          <input type="checkbox" name="free-promo" id="free-promo">
          <label for="free-promo">我要免費宣傳活動</label>
        </div>
        <div class="border-wrapper">
          <label for="promo-title7">宣傳預算</label>
          <span>
            <input type="text" id="promo-title7" placeholder="請輸入您的宣傳預算">
          </span>
        </div>
      </div>

    </div>
<!-- select time -->
    <div class="select-wrapper">
      <span class="promo-time">曝光時間</span>
      <span class="check-wrapper">
        <input type="radio" name="second" id="second-0">
        <label for="second-0">0 秒</label>
        <input type="radio" name="second" id="second-3">
        <label for="second-3">3 秒</label>
        <input type="radio" name="second" id="second-5">
        <label for="second-5">5 秒</label>
        <input type="radio" name="second" id="second-10">
        <label for="second-10">10 秒</label>
        <input type="radio" name="second" id="second-30">
        <label for="second-30">30 秒</label>
        <input type="radio" name="second" id="second-60">
        <label for="second-60">60 秒</label>
      </span>
    </div>
    <div class="content-wrapper">
      <div class="inner-wrapper">
        <span class="timing">單次DM限制曝光時間：<span>0秒</span></span>
        <span class="charge">單次曝光費用：<span>1元/次</span></span>
        <span class="remaining">目前預算可曝光次數：<span>20,000</span> /次</span>
      </div>

    </div>
<!-- form option -->
    <div class="form-options">
      <div class="option cancle">
        <a href="#">
          <span>上一步 | 填寫詳細資訊</span>
        </a>
      </div>
      <div class="option next actived">
        <a href="#">
          <span>SUBMIT | 送出資料</span>
        </a>
      </div>
    </div>

  </div>



<!-- </div> -->

app/views/events/show.html.erb
<% content_for :head do %>
  <meta property="og:url"  content="https://young-brook-5900.herokuapp.com/events/<%= @event.id %>" />
  <meta property="og:title"  content="<%= @event.title %>" />
  <meta proverty="og:locale" content="zh-TW" />
  <meta property="og:image" content="<%= @event.cover.url %>" />
  <meta property="og:description" content="<%= @event.description %>" />
  <meta property="og:site_name"  content="joinfuns" />
  <meta property="fb:app_id" content="652196168244318" />
<% end %>


<div class="dm-page-wrapper">
<!-- navigation path -->
  <div class="dm-page-path">
    <span>頁面路徑 / <%= link_to @event.user.name,host_path(@event.user.id) %> / <%=@event.title%> </span>
  </div>
  <div class="page-promotion">
    <!-- page poster -->
    <div class="poster-wrapper">

      <!-- <img src="http://blog.techartgroup.com/wp-content/uploads/2014/02/pic_news.jpg" alt=""> -->
      <%= image_tag @event.cover.url %>
    </div>
    <!-- page description -->
    <div class="page-description">
      <h2 class="page-title"><%= @event.title %></h2>
      <ul class="page-info">
        <li>
          <span class="date">活動時間：</span><span><%= @event.start_time %></span>~<span><%= @event.end_time %></span>
        </li>
        <li>
          <span class="event">費用資訊：</span><span>城市通話抽獎</span>
        </li>
        <li>
          <span class="times">活動場次：</span><span>活動只有一場次</span>
        </li>
        <li>
          <span class="organizer">主辦單位：</span><span><%= @event.user.name %></span>
        </li>
        <li>
          <span class="sponsor">主辦人：</span><span><%= @event.user.name %></span>
        </li>
        <li>
          <span class="address">地址：</span><span><%= @event.address %></span>
        </li>
        <li>
          <span class="websit">網址：</span><span><%= link_to @event.website %></span>
        </li>
        <li>
          <span class="email">email：</span><span><%= link_to @event.email %></span>
        </li>
        <li>
          <span class="phone">電話：</span><span><%= @event.contact_phone %></span>
        </li>
      </ul>
      <!-- page price -->
      <div class="page-event-price">
        <span>票價資訊</span>
        <!-- price list -->
        <%@event.prices.each do |p| %>
          <div class="price"><span>NT</span><span class="value"><%=p.price%></span></div>
        <% end %>
        <!-- <div class="price actived"><span>NT</span><span class="value">300</span></div>
        <div class="price"><span>NT</span><span class="value">600</span></div>
        <div class="price"><span>NT</span><span class="value">900</span></div> -->

      </div>
      <!-- options -->
      <div class="page-options-wrapper">
        <ul>
          <li>

           <%=link_to "javascript:fbShare('https://young-brook-5900.herokuapp.com/events/#{@event.id}/', '#{@event.title}', '#{@event.description}', '#{@event.cover}', 520, 350, '#{current_user.id}')",:class=>"option share fb-share-button" do%>
              <span class="content">分享活動</span>
           <%end%>

<!--             <a href="#" class="option share fb-share-button" data-href="http://localhost:3000"> -->
<!--
            </a> -->
          </li>
          <li>
            <%= link_to collect_event_path(@event),:method=>"post", :class=>"option favorite",:remote=>true do %>
              <%if @collect %>
                <span>取消收藏</span>
              <% else %>
                <span>收藏活動</span>
              <% end %>
            <% end %>

          </li>
          <li>
            <a href="#" class="option join">
              <span>參加活動去</span>
            </a>
          </li>
        </ul>

      </div>
    </div>
  </div>
  <!-- secondary page -->
  <div class="page-secondary">
    <div class="page-editor">
      <div class="ck-editor">
        <%= @event.description.html_safe %>
      </div>
      <div class="leaveword">
        <span>留言：</span>
        <%= form_for @comment,:url => event_comments_path(@event),:remote=>true do |c|%>
        <!-- <textarea name="leaveword" id="leaveword" cols="30" rows="10"></textarea> -->
        <%= c.text_area :content %>
        <%= c.submit "發表" ,:id =>"commit", :class => "submit" %>
       <!--  <div class="submit">
          <span>送出留言</span>
        </div> -->
        <% end %>
      </div>
      <div class="page-msg-wrapper">
        <%= @event.comments_count %> 則評論
        <% @comments.each do |c|%>
        <!-- <div class="unit-wrapper">
          <div class="avatar">
            <%= image_tag current_user.image %>
          </div>
          <span class="name" title="Hey Mike 塞me">
            <%= current_user.name %>
          </span>
          <div class="leave-msg">
            <span>
              <%= c.content %>
            </span>
          </div>
        </div> -->
          <%= render partial: "partials/comment",:locals => { :c => c }  %>
        <% end %>
      </div>
    </div>
  <!-- right side shorten dm Klein-->
    <div class="shorten-dm-wrapper">
      <div class="main-title">
        <span>熱門活動</span>
      </div>
      <div class="unit-shorten-cover">
<% @events.each do |e| %>
        <div class="unit-shorten-dm">

          <!-- close button -->
          <!-- <i class="shorten-close-btn fa fa-close" role="button"></i> -->

          <div class="shorten-dm-cover" style="background-image: url(<%=e.cover.url %>);">
          </div>
          <div class="info-wrapper">

            <h4 class="title dm"><%=e.title%></h4>
            <!-- shorten dm info -->
            <div class="shorten-dm-info">
              <span class="host">Host：</span>
              <span><%=e.hoster%></span>
            </div>
            <!-- price -->
            <div class="shorten-price">
              <span>Price：</span>
              <!-- price list -->
              <% e.prices.each do |p| %>
                <div class="price" data-behavior="price-tag"><span>NT </span><span class="value"><%=p.price%></span></div>
              <% end %>
              <!-- <div class="price actived"><span>NT</span><span class="value">300</span></div>
              <div class="price"><span>NT</span><span class="value">600</span></div>
              <div class="price"><span>NT</span><span class="value">900</span></div> -->
            </div>
            <!-- option -->
            <div class="option-wrapper">
              <%= link_to event_path(e), class: 'option join' do %>
                <span>參加</span>
              <% end %>
              <div class="join-count">
                <span><%= number_with_delimiter(rand(1..100000), :delimiter => ","  ) %></span>
                <span>Join it</span>
              </div>
            </div>
          </div>
        </div>
<% end %>
      </div>
    </div>

  </div>

</div>
<div id="fb-root"></div>
<%= content_for :handwrite_js do %>


<script>

(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.4&appId=652196168244318";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

function fbShare(url, title, descr, image, winWidth, winHeight, uid) {
    var winTop = (screen.height / 2) - (winHeight / 2);
    var winLeft = (screen.width / 2) - (winWidth / 2);
    window.open('http://www.facebook.com/sharer.php?s=100&p[title]=' + title + '&p[summary]=' + descr + '&p[url]=' + url + '&p[images][0]=' + image, 'sharer', 'top=' + winTop + ',left=' + winLeft + ',toolbar=0,status=0,width=' + winWidth + ',height=' + winHeight + ',uid=' + uid);
}

</script>

<% end %>

app/views/events/show.js.erb
var html='<%= j(render :partial => "partials/dm_panel", :locals => { :event => @event } )%>';

$(".dm-panel-wrapper").replaceWith(html)