config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'prototype#index'

  resources :events, only: [:index, :show, :new, :create] do
    resources :comments, :controller => 'event_comments'
    member do
      post :collect
    end
  end



  resources :subjects, only: [:index, :show, :new, :create]


  resources :orders, only: [:index, :show, :new, :create] do
    get :checkout_allpay, :on => :member
    post "notify", on: :member
  end

  resources :hosts

  get 'beta_sign_in' => 'prototype#sign_in', as: :sign_in
  get 'beta_sign_up' => 'prototype#sign_up', as: :sign_up
  get 'main' => 'prototype#main'
  #get 'subjects' => 'prototype#subjects_index', as: :subjects
  #get 'subject/23' => 'prototype#subject_show', as: :show_subject
  get 'dm_poster' => 'prototype#dm_poster'
  get 'host_page' => 'prototype#host_page'
  get 'host_new_subject' => 'prototype#host_new_subject'
  get 'host_new_event' => 'prototype#host_new_event'
  get 'host_promotion' => 'prototype#host_promotion'

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :user
  has_attached_file :cover, :styles => { :medium => "600x600>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def index
    @subjects = Subject.all
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject= Subject.new(subject_params)
    @subject.user = current_user

    if @subject.save
      flash[:success] = "標案已成功建立！"
      redirect_to subjects_path
    else
      flash[:error] = "請檢查欄位後再試一次。"
      render :new
    end
  end

  def show

    @subject = Event.find(params[:id])

    @subjects = Event.includes(:photos, :prices).all # TODO, show filter out hotest events


  end

  private

  def subject_params
    params.require(:subject).permit(:title, :cover, :link, :email, :address, :price, :phone, :description, :budget, :showtime, :end_time)
  end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/index.html.erb
<div class="subjects-index-wrapper">
  <div class="subjects-container">
    <% @subjects.each do |s|%>
      <div class="subject-unit">
        <div class="subject-inner trans-03s">
          <div class="subject-cover-wrapper" style="background-image: url(<%= s.cover.url %>);"></div>
          <div class="subject-info-wrapper">
            <h3><%= s.title %></h3>

            <div class="progress">
              <% progress = rand(5..100) %>
              <div class="determinate" style="width: <%= progress %>%"></div>
            </div>
            <span class="progress-value">
              <%= progress %>%
            </span>

            <div class="time-info-wrapper">
              <div class="hour">
                <span class='value'><%= rand(0..23).to_s.rjust(2, '0') %></span>
                <span class="unit">hr</span>
              </div>
              <div class="minute">
                <span class='value'><%= rand(0..59).to_s.rjust(2, '0') %></span>
                <span class="unit">min</span>
              </div>
              <div class="second">
                <span class='value'><%= rand(0..59).to_s.rjust(2, '0') %></span>
                <span class="unit">sec</span>
              </div>
            </div>

            <div class="get-button">
              <%= link_to 'Get' %>
              <!-- <a href="#">Get</a> -->
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/subjects/new.html.erb
<!-- navigation path -->
<!-- <div class="host-page-path">
  <span>頁面路徑  / 主辦單位活動列表 / 台北威秀影城</span>
</div> -->
<!-- main wrapper -->
<div class="new-subject-wrapper">
  <div class="new-subject">
    <i class="material-icons">accessibility</i><span><%= current_user.name %> | 新建標案</span>
  </div>
<!-- avatar -->
  <div class="avatar-wrapper">
    <div class="image-wrapper">
     <%= image_tag current_user.image ,width: 100, height: 100 %>
    </div>
    <span class="user-name"><%=current_user.name%></span>
  </div>

  <%=form_for @subject, :html => {:class => "subject-info"} do |f|%>
  <div class="subject-form">
<!-- options -->
  <div class="options">
    <div class="create">
      <%= link_to new_event_path do %>
        <span>Event | 新建活動</span>
      <% end %>
    </div>
    <div class="create actived">
      <a href="#">
        <span>Subject | 新建標案</span>
      </a>
    </div>
  </div>
<!-- description -->
  <div class="step-by-step">
    <div class="step-wrapper">
      <span>在JoinFuns建立的標案將獲得優先曝光</span>
      <div class="circle-wrapper">

        <div class="step actived">
          <span class="circle">1</span>
          <span>建立標案資訊</span>
        </div>

        <div class="step">
          <span class="dots">
            <%= image_tag 'dot-dot-bg.png' %>
          </span>
          <span>&nbsp</span>
        </div>

        <div class="step">
          <span class="circle">2</span>
          <span>選取宣傳工具</span>
        </div>

      </div>
    </div>
  </div>

<!-- subject input 1st -->


    <div class="info-box actived">
      <label for="subject-title1">活動主題</label>
      <span><%= f.text_field :title %></span>
    </div>
    <div class="info-box">
      <label for="subject-title2">主題圖片</label>
      <span>
        <!-- <input type="text" id="subject-title2">
        <a href="" class="select-file">選取檔案</a> -->
        <%= f.file_field :cover %>
      </span>

    </div>
    <div class="info-box">
      <label for="subject-title3">原始商品連結</label>
      <span><%= f.text_field :link %></span>
    </div>
    <div class="info-box">
      <label for="subject-title4">地址</label>
      <span><%= f.text_field :address %></span>
    </div>

<!-- drop selection -->
<!-- #TODO -->
    <div class="section-wrapper">
      <div class="drop-section-wrapper">
        <select>
          <option value="" disabled selected>結案天數</option>
          <option value="1">Option 1</option>
          <option value="2">Option 2</option>
          <option value="3">Option 3</option>
        </select>
      </div>
    </div>
<!-- subject input 2nd -->
    <div class="info-box">
      <label for="subject-title5">商品價格</label>
      <span><%= f.text_field :price %></span>
    </div>
    <div class="info-box">
      <label for="subject-title6">聯絡電話</label>
      <span><%= f.text_field :phone %></span>
    </div>
    <div class="info-box">
      <label for="subject-title7">連絡信箱</label>
      <span><%= f.text_field :email %></span>
    </div>

<!-- ck - editor -->
    <div class="editor-wrapper">
      <span>文案編輯</span>
      <div class="editor">
        <%= f.text_area :description, rows: '3' %>
      </div>
    </div>

<!-- form option -->
    <div class="form-options">
      <div class="option cancle">
        <%= link_to events_path , :'data-no-turbolink' => true do%>
          <span>取消建立</span>
        <% end %>
      </div>
      <div class="option next">
        <a href="#">
          <span>下一步 | 選取宣傳工具</span>
        </a>
      </div>
    </div>
    </div>

 <%= render :partial => "partials/promotion" ,:locals => { :f => f }%>
  <%end%>



</div>

<%= content_for :handwrite_js do %>
  <script>
    $(document).ready(function() {
        $('select').material_select();
        $('.new-promo-wrapper').hide();
        $('.next').on("click",function(){
          $('.subject-form').hide();
          $('.new-promo-wrapper').show();
        });
        $('.cancle').on("click",function(){

          $('.new-promo-wrapper').hide();
          $('.subject-form').show();
        })

      });
  </script>
<% end %>

app/views/subjects/show.html.erb
<% content_for :head do %>
  <meta property="og:url"  content="http://localhost:3000/<%= @subject.id %>" />
  <meta property="og:title"  content="<%= @subject.title %>" />
  <meta proverty="og:locale" content="zh-TW" />
  <meta property="og:image" content="<%= @subject.cover.url %>" />
  <meta property="og:description" content="<%= @subject.description %>" />
  <meta property="og:site_name"  content="joinfuns" />
  <meta property="fb:app_id" content="652196168244318" />
<% end %>


<div class="dm-page-wrapper">
<!-- navigation path -->
  <div class="dm-page-path">
    <span>標案 / <%= link_to @subject.user.name,host_path(@subject.user.id) %> / <%=@subject.title%> </span>
  </div>
  <div class="page-promotion">
    <!-- page poster -->
    <div class="poster-wrapper">

      <!-- <img src="http://blog.techartgroup.com/wp-content/uploads/2014/02/pic_news.jpg" alt=""> -->
      <%= image_tag @subject.cover.url %>
    </div>
    <!-- page description -->
    <div class="page-description">
      <h2 class="page-title"><%= @subject.title %></h2>
      <ul class="page-info">
        <li>
          <span class="date">活動時間：</span><span><%= @subject.start_time %></span>~<span><%= @subject.end_time %></span>
        </li>
        <li>
          <span class="event">費用資訊：</span><span>城市通話抽獎</span>
        </li>
        <li>
          <span class="times">活動場次：</span><span>活動只有一場次</span>
        </li>
        <li>
          <span class="organizer">主辦單位：</span><span><%= @subject.user.name %></span>
        </li>
        <li>
          <span class="sponsor">主辦人：</span><span><%= @subject.user.name %></span>
        </li>
        <li>
          <span class="address">地址：</span><span><%= @subject.address %></span>
        </li>
        <li>
          <span class="websit">網址：</span><span><%= link_to @subject.website %></span>
        </li>
        <li>
          <span class="email">email：</span><span><%= link_to @subject.email %></span>
        </li>
        <li>
          <span class="phone">電話：</span><span><%= @subject.contact_phone %></span>
        </li>
      </ul>
      <!-- page price -->
      <div class="page-event-price">
        <span>票價資訊</span>
        <!-- price list -->
        <%@subject.prices.each do |p| %>
          <div class="price"><span>NT</span><span class="value"><%=p.price%></span></div>
        <% end %>
        <!-- <div class="price actived"><span>NT</span><span class="value">300</span></div>
        <div class="price"><span>NT</span><span class="value">600</span></div>
        <div class="price"><span>NT</span><span class="value">900</span></div> -->

      </div>
      <!-- options -->
      <div class="page-options-wrapper">
        <ul>
          <li>

           <%=link_to "javascript:fbShare('http://alpha.joinfuns.com/event/#{@subject.id}/', '#{@subject.title}', '#{@subject.description}', '#{@subject.cover}', 520, 350, '#{current_user.id}')",:class=>"option share fb-share-button" do%>
              <span class="content">分享活動</span>
           <%end%>

<!--             <a href="#" class="option share fb-share-button" data-href="http://localhost:3000"> -->
<!--
            </a> -->
          </li>
          <li>
            <%= link_to collect_event_path(@subject),:method=>"post", :class=>"option favorite",:remote=>true do %>
              <%if @collect %>
                <span>取消收藏</span>
              <% else %>
                <span>收藏活動</span>
              <% end %>
            <% end %>

          </li>
          <li>
            <a href="#" class="option join">
              <span>參加活動去</span>
            </a>
          </li>
        </ul>

      </div>
    </div>
  </div>
  <!-- secondary page -->
  <div class="page-secondary">
    <div class="page-editor">
      <div class="ck-editor">
        <%= @subject.description.html_safe %>
      </div>
      <div class="leaveword">
        <span>留言：</span>
        <%= form_for @comment,:url => event_comments_path(@subject),:remote=>true do |c|%>
        <!-- <textarea name="leaveword" id="leaveword" cols="30" rows="10"></textarea> -->
        <%= c.text_area :content %>
        <%= c.submit "發表" ,:id =>"commit", :class => "submit" %>
       <!--  <div class="submit">
          <span>送出留言</span>
        </div> -->
        <% end %>
      </div>
      <div class="page-msg-wrapper">
        <%= @subject.comments_count %> 則評論
        <% @comments.each do |c|%>
        <!-- <div class="unit-wrapper">
          <div class="avatar">
            <%= image_tag current_user.image %>
          </div>
          <span class="name" title="Hey Mike 塞me">
            <%= current_user.name %>
          </span>
          <div class="leave-msg">
            <span>
              <%= c.content %>
            </span>
          </div>
        </div> -->
          <%= render partial: "partials/comment",:locals => { :c => c }  %>
        <% end %>
      </div>
    </div>
  <!-- right side shorten dm Klein-->
    <div class="shorten-dm-wrapper">
      <div class="main-title">
        <span>熱門活動</span>
      </div>
      <div class="unit-shorten-cover">
<% @subjects.each do |e| %>
        <div class="unit-shorten-dm">

          <!-- close button -->
          <!-- <i class="shorten-close-btn fa fa-close" role="button"></i> -->

          <div class="shorten-dm-cover" style="background-image: url(<%=e.cover.url %>);">
          </div>
          <div class="info-wrapper">

            <h4 class="title dm"><%=e.title%></h4>
            <!-- shorten dm info -->
            <div class="shorten-dm-info">
              <span class="host">Host：</span>
              <span><%=e.hoster%></span>
            </div>
            <!-- price -->
            <div class="shorten-price">
              <span>Price：</span>
              <!-- price list -->
              <% e.prices.each do |p| %>
                <div class="price" data-behavior="price-tag"><span>NT </span><span class="value"><%=p.price%></span></div>
              <% end %>
              <!-- <div class="price actived"><span>NT</span><span class="value">300</span></div>
              <div class="price"><span>NT</span><span class="value">600</span></div>
              <div class="price"><span>NT</span><span class="value">900</span></div> -->
            </div>
            <!-- option -->
            <div class="option-wrapper">
              <%= link_to event_path(e), class: 'option join' do %>
                <span>參加</span>
              <% end %>
              <div class="join-count">
                <span><%= number_with_delimiter(rand(1..100000), :delimiter => ","  ) %></span>
                <span>Join it</span>
              </div>
            </div>
          </div>
        </div>
<% end %>
      </div>
    </div>

  </div>

</div>
<div id="fb-root"></div>
<%= content_for :handwrite_js do %>


<script>

(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.4&appId=652196168244318";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));

function fbShare(url, title, descr, image, winWidth, winHeight, uid) {
    var winTop = (screen.height / 2) - (winHeight / 2);
    var winLeft = (screen.width / 2) - (winWidth / 2);
    window.open('http://www.facebook.com/sharer.php?s=100&p[title]=' + title + '&p[summary]=' + descr + '&p[url]=' + url + '&p[images][0]=' + image, 'sharer', 'top=' + winTop + ',left=' + winLeft + ',toolbar=0,status=0,width=' + winWidth + ',height=' + winHeight + ',uid=' + uid);
}

</script>

<% end %>